name: Buld and Deploy

on: push # GitHubへのプッシュをトリガーに

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Setup Dependencies
        run: npm ci
      - name: Build
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build # buildが成功した場合のみ実行
    if: "contains(github.ref, 'master')" # masterブランチの場合のみ実行
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup AWS CDK
        run: npm install -g aws-cdk@1.104.0
      - name: Setup Dependencies
        run: npm ci
      - name: Deploy
        run: npm run cdk-deploy
        env:
          AWS_DEFAULT_REGION: ap-northeast-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
